### ISSUE TITLE
[Bug]: AssetRipper GUI crash without error

### ISSUE THREAD

**Issue by sp00ktober** [ds5678/AssetRipper#182] opened 2021-11-28 10:04 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2020.3.10f1 according to the logfile, but should be correct.

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Loaded `globalgamemanagers.assets`, `sharedassets0.assets`, `sharedassets1.assets` and `sharedassets2.assets` (game is called Starsand, its an early access game) and tried to export all. At about 31% AssetRipper just closed itself without any message or warning.

### Relevant log output

[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/7613207/AssetRipper.log)

**Comment by ds5678** [comment] 2021-11-28 18:00
Duplicate of #81

**Closed by ds5678** 2021-11-28 18:00 UTC
Labels: bug
