### ISSUE TITLE
SerializedFile with index 1064958457 was not found in dependencies[Bug]: 

### ISSUE THREAD

**Issue by vale7z4387ruwrejmhsr** [ds5678/AssetRipper#219] opened 2021-12-28 20:44 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

unity 2018.3.9.32286

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

i wanted to export all assets and than this message box showed up wich shouldn't happen obviously
also i know alpha builds are not really that stable but still

### Relevant log output

System.Exception: SerializedFile with index 1064958457 was not found in dependencies
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.FindAsset(Int32 fileIndex, Int64 pathID, Boolean isSafe) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\SerializedFile.cs:line 286
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.FindAsset(Int32 fileIndex, Int64 pathID) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\SerializedFile.cs:line 126
   at AssetRipper.Core.Project.ProjectAssetContainer.FindAsset(Int32 fileIndex, Int64 pathID) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Project\ProjectAssetContainer.cs:line 106
   at AssetRipper.Core.Classes.Misc.PPtr`1.FindAsset(IAssetContainer file) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Classes\Misc\PPtr.cs:line 102
   at AssetRipper.Core.Classes.Misc.PPtr`1.ExportYAML(IExportContainer container) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Classes\Misc\PPtr.cs:line 83
   at AssetRipper.Core.Structure.Assembly.Serializable.SerializablePointer.ExportYAML(IExportContainer container) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\Assembly\Serializable\SerializablePointer.cs:line 30
   at AssetRipper.Core.Structure.Assembly.Serializable.SerializableField.ExportYAML(IExportContainer container, Field& etalon) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\Assembly\Serializable\SerializableField.cs:line 459
   at AssetRipper.Core.Structure.Assembly.Serializable.SerializableStructure.ExportYAML(IExportContainer container) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\Assembly\Serializable\SerializableStructure.cs:line 54
   at AssetRipper.Core.Classes.MonoBehaviourExtensions.MaybeExportYamlForStructure(IMonoBehaviour monoBehaviour, YAMLMappingNode node, IExportContainer container) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Classes\IMonoBehaviour.cs:line 75
   at AssetRipper.Core.Classes.MonoBehaviour.ExportYAMLRoot(IExportContainer container) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\MonoBehaviour.cs:line 77
   at AssetRipper.Core.Classes.Object.Object.ExportYAML(IExportContainer container) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\Object\Object.cs:line 42
   at AssetRipper.Core.UnityObjectBase.ExportYAMLDocument(IExportContainer container) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\UnityObjectBase.cs:line 50
   at AssetRipper.Core.Project.Exporters.YamlExporterBase.Export(IExportContainer container, IEnumerable`1 assets, String path) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\Exporters\YamlExporterBase.cs:line 47
   at AssetRipper.Core.Project.Collections.SceneExportCollection.Export(IProjectAssetContainer container, String dirPath) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Project\Collections\SceneExportCollection.cs:line 138
   at AssetRipper.Core.Project.ProjectExporterBase.Export(GameCollection fileCollection, IEnumerable`1 files, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Project\ProjectExporterBase.cs:line 147
   at AssetRipper.Core.Project.ProjectExporterBase.Export(GameCollection fileCollection, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Project\ProjectExporterBase.cs:line 67
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Export(CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 91
   at AssetRipper.Library.Ripper.ExportProject(String exportPath, IEnumerable`1 assets) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 144
   at AssetRipper.Library.Ripper.ExportProject(String exportPath) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 128
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, String toRoot, Action onSuccess, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipperGUI\Managers\UIExportManager.cs:line 46

**Comment by ds5678** [comment] 2021-12-28 20:53
duplicate of #172

**Closed by ds5678** 2021-12-28 20:53 UTC
Labels: bug
