### ISSUE TITLE
Failed to export game content: SerializedFile with index 1058982946 was not found in dependencies when trying to export all assets from game[Bug]: 

### ISSUE THREAD

**Issue by dan771** [ds5678/AssetRipper#217] opened 2021-12-26 11:14 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

Unity 2020.2.5.14861631

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Uploaded full top level parent folder in and failed to export

### Relevant log output

[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/7776894/AssetRipper.log)

**Comment by ds5678** [comment] 2021-12-26 15:39
duplicate of #172

**Closed by ds5678** 2021-12-26 15:39 UTC
Labels: bug
