### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by xAstroBoy** [ds5678/AssetRipper#174] opened 2021-11-24 09:14 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2019.1.9 (I think) (VRChat)

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

I tried AssetRipping a world to get to the animation and it crashes at 70% , somehow.

### Relevant log output

[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/7594302/AssetRipper.log)

**Comment by ds5678** [comment] 2021-11-24 09:19
Duplicate of #81

**Closed by ds5678** 2021-11-24 09:19 UTC
Labels: bug
