### ISSUE TITLE
[Bug]: Vrchat Data avatar folder

### ISSUE THREAD

**Issue by LeoFeroz** [ds5678/AssetRipper#21] opened 2021-08-06 02:54 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

5.x.x 2019.4.29f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

I'm trying to rip the vrcat avatar files that have the name _data
File Example:
[__data.zip](https://github.com/ds5678/AssetRipper/files/6942697/__data.zip)

### Relevant log output

[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/7028055/AssetRipper.log)

**Comment by ds5678** [comment] 2021-08-06 04:02
Hi, this is a duplicate of #5 which I am currently working on.

**Comment by LeoFeroz** [comment] 2021-08-22 20:00
> Olá, esta é uma duplicata de [# 5 na](https://github.com/ds5678/AssetRipper/issues/5) qual estou trabalhando no momento.

hello after the latest updates ripper can read vrcaht .vrca files but it can't read _data files
that they are the vrca files but with some kind of encryption this happened when the unity used in the game was updated from 2018 to 2019
unityripper was able to extract these files

Examples:
[Archives.zip](https://github.com/ds5678/AssetRipper/files/7028053/Archives.zip)
New Log

**Comment by ds5678** [comment] 2021-08-23 01:30
At this time, the AssetRipper team does not offer technical support for ripping VR Chat or user content intended for VR Chat.

**Closed by ds5678** 2021-08-23 01:30 UTC
Labels: bug
