### ISSUE TITLE
[Bug]: Crashed on android game.

### ISSUE THREAD

**Issue by haiderali6426** [ds5678/AssetRipper#18] opened 2021-08-02 19:21 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

i think it was the 2020 unity or 2019 I can't find the version using UABE software

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

I just converted the .apk to .zip and dragged the folder in asset ripper and this error came.

### Relevant log output

Game name: (please, specify the game name)
Engine version: (specify engine version, if known)
Platform: (specify platform, if known)

Error message: Some data left

Stack trace:    at AssetRipper.Lz4.Lz4DecodeStream.ReadBuffer(Stream stream, Int64 count)
   at AssetRipper.Parser.Files.BundleFile.BundleFileScheme.ReadFileStreamMetadata(Stream stream, Int64 basePosition)
   at AssetRipper.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream)
   at AssetRipper.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream, String filePath, String fileName)
   at AssetRipper.Parser.Files.BundleFile.BundleFile.ReadScheme(Stream stream, String filePath, String fileName)
   at AssetRipper.Structure.GameCollection.ReadScheme(SmartStream stream, String filePath, String fileName)
   at AssetRipper.Structure.GameCollection.LoadScheme(String filePath, String fileName)
   at AssetRipper.Structure.GameStructure.GameStructure.ProcessPlatformStructure(GameStructureProcessor processor, PlatformGameStructure structure)
   at AssetRipper.Structure.GameStructure.GameStructure.Load(List`1 paths, LayoutInfo layinfo)
   at AssetRipper.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, LayoutInfo layinfo)
   at AssetRipper.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths)
   at AssetRipperGUI.MainWindow.LoadFiles(Object data)

**Comment by haiderali6426** [comment] 2021-08-02 19:33
[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/6919207/AssetRipper.log)

**Comment by haiderali6426** [comment] 2021-08-02 19:33
also if i open this file with asset studio it will work

**Comment by haiderali6426** [comment] 2021-08-02 19:37
I tried this on the per-released version, but the error came.

**Comment by ds5678** [comment] 2021-08-02 21:05
Hi, this is a duplicate of #5. When I resolve that,issue, this should work too.

**Comment by ds5678** [comment] 2021-08-19 00:48
Hi, this should have been resolved in a recent commit. If your issue persists on the latest alpha build, please post a new issue.

**Closed by ds5678** 2021-08-19 00:48 UTC
Labels: bug
