### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mayura33** [ds5678/AssetRipper#8] opened 2021-07-26 09:28 UTC
### Are you on the latest version of AssetRipper?

- [X] Yes, I'm on the latest version of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

Play store URL : https://play.google.com/store/apps/details?id=com.pixpop.musical.videoeditor
Unity version : 2019.4.18f1
Got this Error : 
![image](https://user-images.githubusercontent.com/33602207/126966655-79ddfb31-0587-48c9-b8f4-9fe339a67865.png)

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Please have a look into this SS.
Let me know if you want to know anything else.

**Comment by ds5678** [comment] 2021-07-26 15:37
This is a duplicate of #5, which is currently being worked on.

**Closed by ds5678** 2021-07-26 15:37 UTC
Labels: bug
