### ISSUE TITLE
[Bug]: Failed to load game content:Read 56 but expected 60 for asset type MeshCollider

### ISSUE THREAD

**Issue by qq1035732175** [ds5678/AssetRipper#157] opened 2021-10-31 12:18 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

Unity 5.4.1f1 

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

The game was originally encrypted. After I decrypted it with the bms script, there was no problem importing it using assetsStudioGUI, but an error occurred when using Unity Ripper: Failed to load game content:Read 56 but expected 60 for asset type MeshCollider

Failed to load game content: Read 48 but expected 88 for asset type MeshCollider

### Relevant log output

System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 10.0.19041.0
System : Operating System: Windows x64
System : AssetRipper Version: 0.1.7.2
System : AssetRipper Build Type: Release x64 Published
System : Current UTC Time: 2021/10/31 12:15:55
System : Loading locale en_US.json
: Language English (United Kingdom) isActive False
: Language English (United States) isActive True
: Language español isActive False
: Language Indonesia isActive False
: Language italiano isActive False
: Language português (Brasil) isActive False
: Language 中文（简体） isActive False
System : Available languages: en_GB, en_US, es, id, it, pt_BR, zh_Hans
General : Attempting to read files from F:\OUT\00ada5b5aa533e37741ccf0aaab3d3a9.unity3d
Import : Game file '00ada5b5aa533e37741ccf0aaab3d3a9.unity3d' has been found
Import : Mixed game structure has been found for 1 path(s)
Import [Warning] : Dependency 'library/unity default resources' wasn't found
Import [Warning] : Dependency 'archive:/cab-02e0dd48530ecad57d769201daa02c72/cab-02e0dd48530ecad57d769201daa02c72' wasn't found
Import [Warning] : Dependency 'archive:/cab-03c1d6bf884cf3946e05dacbb376ea1e/cab-03c1d6bf884cf3946e05dacbb376ea1e' wasn't found
Import [Warning] : Dependency 'archive:/cab-05a7a521a045b78c92ff5bd14e01064e/cab-05a7a521a045b78c92ff5bd14e01064e' wasn't found
Import [Warning] : Dependency 'archive:/cab-0feb7338fd13eb86d93885443e03d8a9/cab-0feb7338fd13eb86d93885443e03d8a9' wasn't found
Import [Warning] : Dependency 'archive:/cab-118a90e1f48539f50bdd7086a708d0c9/cab-118a90e1f48539f50bdd7086a708d0c9' wasn't found
Import [Warning] : Dependency 'archive:/cab-16f595c4f694fe41eba5c46fd03d671e/cab-16f595c4f694fe41eba5c46fd03d671e' wasn't found
Import [Warning] : Dependency 'archive:/cab-188bdfae0bb55c47b05882db31b1f93d/cab-188bdfae0bb55c47b05882db31b1f93d' wasn't found
Import [Warning] : Dependency 'archive:/cab-23e93999045d405707b0b324d8be53fd/cab-23e93999045d405707b0b324d8be53fd' wasn't found
Import [Warning] : Dependency 'archive:/cab-2552396447da5407a7796846259cdd96/cab-2552396447da5407a7796846259cdd96' wasn't found
Import [Warning] : Dependency 'archive:/cab-26983ad51cd9f7024e0f2d478ac30b57/cab-26983ad51cd9f7024e0f2d478ac30b57' wasn't found
Import [Warning] : Dependency 'archive:/cab-27491ecb8ea235b70f1306ed215bf671/cab-27491ecb8ea235b70f1306ed215bf671' wasn't found
Import [Warning] : Dependency 'archive:/cab-28eb0b635bc4c4e3e159a0b485daa4bd/cab-28eb0b635bc4c4e3e159a0b485daa4bd' wasn't found
Import [Warning] : Dependency 'archive:/cab-2d60a8443d7fea1a2bd255e1659ae583/cab-2d60a8443d7fea1a2bd255e1659ae583' wasn't found
Import [Warning] : Dependency 'archive:/cab-3184a106ffc689150a19f2c93eb38b4a/cab-3184a106ffc689150a19f2c93eb38b4a' wasn't found
Import [Warning] : Dependency 'archive:/cab-3199f6da54c416f8adfb11df3345b91a/cab-3199f6da54c416f8adfb11df3345b91a' wasn't found
Import [Warning] : Dependency 'archive:/cab-31a310afd806cb0fb5bf5b3c3624360e/cab-31a310afd806cb0fb5bf5b3c3624360e' wasn't found
Import [Warning] : Dependency 'archive:/cab-31b4810c2781dac288e3e922fd196654/cab-31b4810c2781dac288e3e922fd196654' wasn't found
Import [Warning] : Dependency 'archive:/cab-3378b8084b490a6b068e204153851aa2/cab-3378b8084b490a6b068e204153851aa2' wasn't found
Import [Warning] : Dependency 'archive:/cab-352691977d03d38d8433276f299b6b36/cab-352691977d03d38d8433276f299b6b36' wasn't found
Import [Warning] : Dependency 'archive:/cab-3698beda148e9ca2a321cb460a64c5f7/cab-3698beda148e9ca2a321cb460a64c5f7' wasn't found
Import [Warning] : Dependency 'archive:/cab-3be5432b52cc6a2512356c17be458375/cab-3be5432b52cc6a2512356c17be458375' wasn't found
Import [Warning] : Dependency 'archive:/cab-3d412c556c02c0c378639b0a3f8b240f/cab-3d412c556c02c0c378639b0a3f8b240f' wasn't found
Import [Warning] : Dependency 'archive:/cab-44caf8ca96ec27aab68d1ffb3f42e1ce/cab-44caf8ca96ec27aab68d1ffb3f42e1ce' wasn't found
Import [Warning] : Dependency 'archive:/cab-44e6417cd179a31d1fa643bc4d0a8cdd/cab-44e6417cd179a31d1fa643bc4d0a8cdd' wasn't found
Import [Warning] : Dependency 'archive:/cab-459a673239211e245ecc16911f83329a/cab-459a673239211e245ecc16911f83329a' wasn't found
Import [Warning] : Dependency 'archive:/cab-46526fec619d7f80195b0958ec7a0d25/cab-46526fec619d7f80195b0958ec7a0d25' wasn't found
Import [Warning] : Dependency 'archive:/cab-47fbaa5677fdc0a7dd945f033fabae1f/cab-47fbaa5677fdc0a7dd945f033fabae1f' wasn't found
Import [Warning] : Dependency 'archive:/cab-48e1933f09244b2cd389addaeeef4fec/cab-48e1933f09244b2cd389addaeeef4fec' wasn't found
Import [Warning] : Dependency 'archive:/cab-4df03b272ce6b58dfdf2e1712f91c98f/cab-4df03b272ce6b58dfdf2e1712f91c98f' wasn't found
Import [Warning] : Dependency 'archive:/cab-4f30757e64ac9f1f15e877df265e957a/cab-4f30757e64ac9f1f15e877df265e957a' wasn't found
Import [Warning] : Dependency 'archive:/cab-4fd454db95b7e6605f4a70eaf0f86d1b/cab-4fd454db95b7e6605f4a70eaf0f86d1b' wasn't found
Import [Warning] : Dependency 'archive:/cab-544367f725ad5dcc0f23306ceb03116f/cab-544367f725ad5dcc0f23306ceb03116f' wasn't found
Import [Warning] : Dependency 'archive:/cab-54f19b581eef4a515258fa0f52e7e270/cab-54f19b581eef4a515258fa0f52e7e270' wasn't found
Import [Warning] : Dependency 'archive:/cab-556ebe8894ea176d2933ba361a92efc9/cab-556ebe8894ea176d2933ba361a92efc9' wasn't found
Import [Warning] : Dependency 'archive:/cab-56f77f1bdc6f376bf39c16c5d5388784/cab-56f77f1bdc6f376bf39c16c5d5388784' wasn't found
Import [Warning] : Dependency 'archive:/cab-58fec94bcf1d16331a0c6b5caf90e816/cab-58fec94bcf1d16331a0c6b5caf90e816' wasn't found
Import [Warning] : Dependency 'archive:/cab-5b34d29751bb260d81a25fe8e6d84757/cab-5b34d29751bb260d81a25fe8e6d84757' wasn't found
Import [Warning] : Dependency 'archive:/cab-5c07987fa7e610069c07be5d85c024bd/cab-5c07987fa7e610069c07be5d85c024bd' wasn't found
Import [Warning] : Dependency 'archive:/cab-5e1e3dc81f538eb2c55fde15da8434b3/cab-5e1e3dc81f538eb2c55fde15da8434b3' wasn't found
Import [Warning] : Dependency 'archive:/cab-5f62f5b0e1667da1a74348126cb705cc/cab-5f62f5b0e1667da1a74348126cb705cc' wasn't found
Import [Warning] : Dependency 'archive:/cab-6008272a75867df21c84d9dc902ef9d8/cab-6008272a75867df21c84d9dc902ef9d8' wasn't found
Import [Warning] : Dependency 'archive:/cab-60cead2779a4fd980bcdf11d50a1cc0d/cab-60cead2779a4fd980bcdf11d50a1cc0d' wasn't found
Import [Warning] : Dependency 'archive:/cab-61b723a383bc4e047c60f26ed9360ad6/cab-61b723a383bc4e047c60f26ed9360ad6' wasn't found
Import [Warning] : Dependency 'archive:/cab-61bacb251bb7f608f495e46555ed63a5/cab-61bacb251bb7f608f495e46555ed63a5' wasn't found
Import [Warning] : Dependency 'archive:/cab-6234288bacc8e3d53b269b42ee0cd822/cab-6234288bacc8e3d53b269b42ee0cd822' wasn't found
Import [Warning] : Dependency 'archive:/cab-64d5f06dcf7ae71d3f5fcbd6ade1f89f/cab-64d5f06dcf7ae71d3f5fcbd6ade1f89f' wasn't found
Import [Warning] : Dependency 'archive:/cab-66fa76b9ef7149342a1ecdc9677da606/cab-66fa76b9ef7149342a1ecdc9677da606' wasn't found
Import [Warning] : Dependency 'archive:/cab-67e6bb85aff05c90cb0a2e179fc11cc2/cab-67e6bb85aff05c90cb0a2e179fc11cc2' wasn't found
Import [Warning] : Dependency 'archive:/cab-6ae062e37d0db8d337204e194c2fb574/cab-6ae062e37d0db8d337204e194c2fb574' wasn't found
Import [Warning] : Dependency 'archive:/cab-6b79ec8762304564d493f730f2e58625/cab-6b79ec8762304564d493f730f2e58625' wasn't found
Import [Warning] : Dependency 'archive:/cab-6e91489ede7142c6d88fbd64250ec60c/cab-6e91489ede7142c6d88fbd64250ec60c' wasn't found
Import [Warning] : Dependency 'archive:/cab-71509643dfed86a22304bf6783840a5f/cab-71509643dfed86a22304bf6783840a5f' wasn't found
Import [Warning] : Dependency 'archive:/cab-73215dba1080c4fb4322338c6591ac19/cab-73215dba1080c4fb4322338c6591ac19' wasn't found
Import [Warning] : Dependency 'archive:/cab-771f66ef2622b9b833f5f02004ff1878/cab-771f66ef2622b9b833f5f02004ff1878' wasn't found
Import [Warning] : Dependency 'archive:/cab-7b8eb6a4fdec3a6ce9d9e7bcb468edd2/cab-7b8eb6a4fdec3a6ce9d9e7bcb468edd2' wasn't found
Import [Warning] : Dependency 'archive:/cab-7c19e6b682ef7ca67937c0c3319ce63d/cab-7c19e6b682ef7ca67937c0c3319ce63d' wasn't found
Import [Warning] : Dependency 'archive:/cab-7f0ee75c9a91d86ee4a1893fd354af06/cab-7f0ee75c9a91d86ee4a1893fd354af06' wasn't found
Import [Warning] : Dependency 'archive:/cab-807917f9afd3167dd3bb9d3f2ac1eec0/cab-807917f9afd3167dd3bb9d3f2ac1eec0' wasn't found
Import [Warning] : Dependency 'archive:/cab-80af3995345260b34fdcd50684126073/cab-80af3995345260b34fdcd50684126073' wasn't found
Import [Warning] : Dependency 'archive:/cab-81371412b380f7cbfbb494cb3bc0bfe7/cab-81371412b380f7cbfbb494cb3bc0bfe7' wasn't found
Import [Warning] : Dependency 'archive:/cab-81e3cda1acb91e5f2ea71fe9b40353c7/cab-81e3cda1acb91e5f2ea71fe9b40353c7' wasn't found
Import [Warning] : Dependency 'archive:/cab-84193322ac1c7bc7a5b1d7f46e00e11a/cab-84193322ac1c7bc7a5b1d7f46e00e11a' wasn't found
Import [Warning] : Dependency 'archive:/cab-86368e4fac4f15c9297800cf022f9b77/cab-86368e4fac4f15c9297800cf022f9b77' wasn't found
Import [Warning] : Dependency 'archive:/cab-874442358c6a8ab33328cdc534dabc66/cab-874442358c6a8ab33328cdc534dabc66' wasn't found
Import [Warning] : Dependency 'archive:/cab-874d541665ebb8f701c7a54388498b53/cab-874d541665ebb8f701c7a54388498b53' wasn't found
Import [Warning] : Dependency 'archive:/cab-880db2234f2958e3c7561745fd3ce29c/cab-880db2234f2958e3c7561745fd3ce29c' wasn't found
Import [Warning] : Dependency 'archive:/cab-88b002ab479576b21303fed5dfcd77f2/cab-88b002ab479576b21303fed5dfcd77f2' wasn't found
Import [Warning] : Dependency 'archive:/cab-894b1761af5f13289aec04c8d9c19054/cab-894b1761af5f13289aec04c8d9c19054' wasn't found
Import [Warning] : Dependency 'archive:/cab-8c8fb751a4583cf8b9db371496ae5e81/cab-8c8fb751a4583cf8b9db371496ae5e81' wasn't found
Import [Warning] : Dependency 'archive:/cab-8d3fddb4ee445b6762efdfd7ba11d643/cab-8d3fddb4ee445b6762efdfd7ba11d643' wasn't found
Import [Warning] : Dependency 'archive:/cab-8f838e928995e98e23e1908515f3bd1c/cab-8f838e928995e98e23e1908515f3bd1c' wasn't found
Import [Warning] : Dependency 'archive:/cab-92b223af136d37770269a27005f4a7c2/cab-92b223af136d37770269a27005f4a7c2' wasn't found
Import [Warning] : Dependency 'archive:/cab-92dbb6e3dfda07f8c8ca69e2394a9f11/cab-92dbb6e3dfda07f8c8ca69e2394a9f11' wasn't found
Import [Warning] : Dependency 'archive:/cab-940c9b4e23522ab79240b21ddc03c80b/cab-940c9b4e23522ab79240b21ddc03c80b' wasn't found
Import [Warning] : Dependency 'archive:/cab-95575cfe977834f6a22c730575c48a75/cab-95575cfe977834f6a22c730575c48a75' wasn't found
Import [Warning] : Dependency 'archive:/cab-95c2543538419cebdbb872f3c373a51c/cab-95c2543538419cebdbb872f3c373a51c' wasn't found
Import [Warning] : Dependency 'archive:/cab-998a0202274b7c388ac15418beff1f46/cab-998a0202274b7c388ac15418beff1f46' wasn't found
Import [Warning] : Dependency 'archive:/cab-9c54d39a9088016dfa5c38f539875862/cab-9c54d39a9088016dfa5c38f539875862' wasn't found
Import [Warning] : Dependency 'archive:/cab-a1163c99a57df0d2e23110477d02aed6/cab-a1163c99a57df0d2e23110477d02aed6' wasn't found
Import [Warning] : Dependency 'archive:/cab-a27731525f2df48c24c0da0e839e0a89/cab-a27731525f2df48c24c0da0e839e0a89' wasn't found
Import [Warning] : Dependency 'archive:/cab-a37d756dcc45dd69333785336467988d/cab-a37d756dcc45dd69333785336467988d' wasn't found
Import [Warning] : Dependency 'archive:/cab-a7e246e7027751a3a20a8e8ab586a5fc/cab-a7e246e7027751a3a20a8e8ab586a5fc' wasn't found
Import [Warning] : Dependency 'archive:/cab-a7ed1df3a9690dd1b34999b81f331979/cab-a7ed1df3a9690dd1b34999b81f331979' wasn't found
Import [Warning] : Dependency 'archive:/cab-a867a50fe266e8e0baec8d04aea9431b/cab-a867a50fe266e8e0baec8d04aea9431b' wasn't found
Import [Warning] : Dependency 'archive:/cab-a8c31554e179b8a5feb2e0d3a8ac72a1/cab-a8c31554e179b8a5feb2e0d3a8ac72a1' wasn't found
Import [Warning] : Dependency 'archive:/cab-a9bbb9b04050429738fd7e54e8ca6886/cab-a9bbb9b04050429738fd7e54e8ca6886' wasn't found
Import [Warning] : Dependency 'archive:/cab-aa8bb98c9defdb8eb1248f0217fea1cd/cab-aa8bb98c9defdb8eb1248f0217fea1cd' wasn't found
Import [Warning] : Dependency 'archive:/cab-add36d050b223f791ab2bc5817b7600f/cab-add36d050b223f791ab2bc5817b7600f' wasn't found
Import [Warning] : Dependency 'archive:/cab-b223982ba6403ad3f34aea0dc295d282/cab-b223982ba6403ad3f34aea0dc295d282' wasn't found
Import [Warning] : Dependency 'archive:/cab-b57eb688236efddc32c5a35601a122f4/cab-b57eb688236efddc32c5a35601a122f4' wasn't found
Import [Warning] : Dependency 'archive:/cab-b70b7f7fb3f90caa504a61a730e2f380/cab-b70b7f7fb3f90caa504a61a730e2f380' wasn't found
Import [Warning] : Dependency 'archive:/cab-b7980e16518517a36eb09171701a9397/cab-b7980e16518517a36eb09171701a9397' wasn't found
Import [Warning] : Dependency 'archive:/cab-baaa0a8b0cc22d1231e84d2bd23c23ab/cab-baaa0a8b0cc22d1231e84d2bd23c23ab' wasn't found
Import [Warning] : Dependency 'archive:/cab-bc411f9042e3528acfeacbe7c082bf9b/cab-bc411f9042e3528acfeacbe7c082bf9b' wasn't found
Import [Warning] : Dependency 'archive:/cab-bf489e8213db5aaa558e571b077d5c02/cab-bf489e8213db5aaa558e571b077d5c02' wasn't found
Import [Warning] : Dependency 'archive:/cab-c1183b99b72773d08da3c145dfbc27b7/cab-c1183b99b72773d08da3c145dfbc27b7' wasn't found
Import [Warning] : Dependency 'archive:/cab-c27c5cccde72a6745544a230a3db5fe1/cab-c27c5cccde72a6745544a230a3db5fe1' wasn't found
Import [Warning] : Dependency 'archive:/cab-c62251c3a1ad809747126e6c68911929/cab-c62251c3a1ad809747126e6c68911929' wasn't found
Import [Warning] : Dependency 'archive:/cab-c6a75fcd4f15e4d68acf3ba944c53437/cab-c6a75fcd4f15e4d68acf3ba944c53437' wasn't found
Import [Warning] : Dependency 'archive:/cab-c74ab653c8050d67751aa2f94ee7bcf7/cab-c74ab653c8050d67751aa2f94ee7bcf7' wasn't found
Import [Warning] : Dependency 'archive:/cab-cdfafe7bea2052b5d93fd4cb755519a9/cab-cdfafe7bea2052b5d93fd4cb755519a9' wasn't found
Import [Warning] : Dependency 'archive:/cab-cf5a02d9f757d7d46e23389ab6057dad/cab-cf5a02d9f757d7d46e23389ab6057dad' wasn't found
Import [Warning] : Dependency 'archive:/cab-d0435a79d4e2f377126fe3310af2e53e/cab-d0435a79d4e2f377126fe3310af2e53e' wasn't found
Import [Warning] : Dependency 'archive:/cab-d075d04667c468c13e4a14048f722868/cab-d075d04667c468c13e4a14048f722868' wasn't found
Import [Warning] : Dependency 'archive:/cab-d0b176721ea40bcc56a28f2b1af4b3f3/cab-d0b176721ea40bcc56a28f2b1af4b3f3' wasn't found
Import [Warning] : Dependency 'archive:/cab-d4ca7a2f5066959b28dea609cb53a37b/cab-d4ca7a2f5066959b28dea609cb53a37b' wasn't found
Import [Warning] : Dependency 'archive:/cab-d7200f2e98d2f793c2b34c6658aab9b0/cab-d7200f2e98d2f793c2b34c6658aab9b0' wasn't found
Import [Warning] : Dependency 'archive:/cab-d8c1670132d0399c19669ab0fd5dd728/cab-d8c1670132d0399c19669ab0fd5dd728' wasn't found
Import [Warning] : Dependency 'archive:/cab-dbb73e17a479b4dd906d05858423ff49/cab-dbb73e17a479b4dd906d05858423ff49' wasn't found
Import [Warning] : Dependency 'archive:/cab-de7f99f13cf7b16411014327eac6160b/cab-de7f99f13cf7b16411014327eac6160b' wasn't found
Import [Warning] : Dependency 'archive:/cab-df0b1da336e656904f55028cb2a28ece/cab-df0b1da336e656904f55028cb2a28ece' wasn't found
Import [Warning] : Dependency 'archive:/cab-e00bbb549cccb99ed77c9f648fd7835f/cab-e00bbb549cccb99ed77c9f648fd7835f' wasn't found
Import [Warning] : Dependency 'archive:/cab-e1cfb45b25a5824a4fd97a6b1aec5360/cab-e1cfb45b25a5824a4fd97a6b1aec5360' wasn't found
Import [Warning] : Dependency 'archive:/cab-e4bf10a1245d279acf1a5b0ec5be7432/cab-e4bf10a1245d279acf1a5b0ec5be7432' wasn't found
Import [Warning] : Dependency 'archive:/cab-e53081e18182cf4fca8f5d5c29350b97/cab-e53081e18182cf4fca8f5d5c29350b97' wasn't found
Import [Warning] : Dependency 'archive:/cab-e55f9acf985e5d7799abb4ceed0f9ded/cab-e55f9acf985e5d7799abb4ceed0f9ded' wasn't found
Import [Warning] : Dependency 'archive:/cab-e5a71f02f624585e7d4ff2925247ffa1/cab-e5a71f02f624585e7d4ff2925247ffa1' wasn't found
Import [Warning] : Dependency 'archive:/cab-e6413ea6e999aa2a3d78262508a51342/cab-e6413ea6e999aa2a3d78262508a51342' wasn't found
Import [Warning] : Dependency 'archive:/cab-e92ba340b7bfc8f28d70cdbe28907d85/cab-e92ba340b7bfc8f28d70cdbe28907d85' wasn't found
Import [Warning] : Dependency 'archive:/cab-ead947f604616dad2f26f02240a59b3d/cab-ead947f604616dad2f26f02240a59b3d' wasn't found
Import [Warning] : Dependency 'archive:/cab-eb2d2b0918c6cad612ae19f56e2fa92c/cab-eb2d2b0918c6cad612ae19f56e2fa92c' wasn't found
Import [Warning] : Dependency 'archive:/cab-ed75c95eeabeec70e0db667722235b00/cab-ed75c95eeabeec70e0db667722235b00' wasn't found
Import [Warning] : Dependency 'archive:/cab-ee9f673cd9435adfa2e934b1700b7de7/cab-ee9f673cd9435adfa2e934b1700b7de7' wasn't found
Import [Warning] : Dependency 'archive:/cab-f431632f23b8c64085799606ba49489c/cab-f431632f23b8c64085799606ba49489c' wasn't found
Import [Warning] : Dependency 'archive:/cab-f4c000299446280a9ba76dac2db1f6f3/cab-f4c000299446280a9ba76dac2db1f6f3' wasn't found
Import [Warning] : Dependency 'archive:/cab-f5b8b288330539f0cb5aad0ca51b194d/cab-f5b8b288330539f0cb5aad0ca51b194d' wasn't found
Import [Warning] : Dependency 'archive:/cab-f7845eaf26adbf38059e2775225e81da/cab-f7845eaf26adbf38059e2775225e81da' wasn't found
Import [Warning] : Dependency 'archive:/cab-f79d44fad5474405e056abfe8bec29bd/cab-f79d44fad5474405e056abfe8bec29bd' wasn't found
Import [Warning] : Dependency 'archive:/cab-fb3f6689c2a325e798d5873496c25ffa/cab-fb3f6689c2a325e798d5873496c25ffa' wasn't found
Import [Warning] : Dependency 'archive:/cab-fd846f2c7e9a95c53b1c7e25c515c099/cab-fd846f2c7e9a95c53b1c7e25c515c099' wasn't found
Import [Warning] : Dependency 'archive:/cab-ff03f63ca776110075a0afad69f2880c/cab-ff03f63ca776110075a0afad69f2880c' wasn't found
Import : Files use the 'Unknown' scripting backend.
[Error] : SerializedFileException: v:2019.4.13f1 p:StandaloneWin64Player t:MeshCollider n:buildplayer-map_1003_0715
Path:F:\OUT\00ada5b5aa533e37741ccf0aaab3d3a9.unity3d
Message: Read 48 but expected 88 for asset type MeshCollider
StackTrace:    at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Parser/Files/SerializedFile/SerializedFile.cs:line 338
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, ObjectInfo& info) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Parser/Files/SerializedFile/SerializedFile.cs:line 311
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadData(Stream stream) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Parser/Files/SerializedFile/SerializedFile.cs:line 260
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadFile(SerializedFile file) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Structure/GameStructure/GameProcessorContext.cs:line 38
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadSerializedFiles() in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Structure/GameStructure/GameProcessorContext.cs:line 30
   at AssetRipper.Core.Structure.GameStructure.GameStructureProcessor.ProcessSchemes(GameCollection fileCollection) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Structure/GameStructure/GameStructureProcessor.cs:line 92
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(List`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Structure/GameStructure/GameStructure.cs:line 89
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Structure/GameStructure/GameStructure.cs:line 35
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Structure/GameStructure/GameStructure.cs:line 27
   at AssetRipper.Library.Ripper.Load(IReadOnlyList`1 paths) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperLibrary/Ripper.cs:line 88
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperGUI/Managers/UIImportManager.cs:line 24

**Comment by ds5678** [comment] 2021-10-31 12:26
Hi, thank you for submitting a bug report. Unfortunately, I'm not currently open to investigating bugs with this error message:
```
Read __ but expected __ for asset type ____________
```
I have been working on a universal solution, which upon completion will mark the shift to AssetRipper `0.2.x.x`. Please keep an eye out for that in the coming weeks.

**Comment by ds5678** [comment] 2021-11-08 19:23
Duplicate of #164

**Closed** 2021-11-08 19:23 UTC
Labels: bug
