### ISSUE TITLE
[Other]: 

### ISSUE THREAD

**Issue by bnmtyhgunec1** [ds5678/AssetRipper#85] opened 2021-09-13 13:07 UTC
### Describe the issue

Game name: (please, specify the game name)
Engine version: 2019.3.0a5
Platform: StandaloneWinPlayer
File name: unity default resources

Error message: Error during reading of asset type Shader

Inner message: System.Exception: End of stream. Read 3816856, expected 1684302152 bytes
   at AssetRipper.Core.IO.Endian.EndianReader.ReadStringBuffer(Int32 size) in C:\Users\Jeremy\source\repos\AssetRipper\AssetRipperCore\IO\Endian\EndianReader.cs:line 717
   at AssetRipper.Core.IO.Asset.AssetReader.ReadString() in C:\Users\Jeremy\source\repos\AssetRipper\AssetRipperCore\IO\Asset\AssetReader.cs:line 34
   at AssetRipper.Core.Classes.Shader.SerializedShader.SerializedShader.Read(AssetReader reader) in C:\Users\Jeremy\source\repos\AssetRipper\AssetRipperCore\Classes\Shader\SerializedShader\SerializedShader.cs:line 28
   at AssetRipper.Core.Classes.Shader.Shader.Read(AssetReader reader) in C:\Users\Jeremy\source\repos\AssetRipper\AssetRipperCore\Classes\Shader\Shader.cs:line 97
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in C:\Users\Jeremy\source\repos\AssetRipper\AssetRipperCore\Parser\Files\SerializedFile\SerializedFile.cs:line 329

Stack trace:    at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in C:\Users\Jeremy\source\repos\AssetRipper\AssetRipperCore\Parser\Files\SerializedFile\SerializedFile.cs:line 333
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, ObjectInfo& info) in C:\Users\Jeremy\source\repos\AssetRipper\AssetRipperCore\Parser\Files\SerializedFile\SerializedFile.cs:line 311
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadData(Stream stream) in C:\Users\Jeremy\source\repos\AssetRipper\AssetRipperCore\Parser\Files\SerializedFile\SerializedFile.cs:line 260
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadFile(SerializedFile file) in C:\Users\Jeremy\source\repos\AssetRipper\AssetRipperCore\Structure\GameStructure\GameProcessorContext.cs:line 33
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadSerializedFiles() in C:\Users\Jeremy\source\repos\AssetRipper\AssetRipperCore\Structure\GameStructure\GameProcessorContext.cs:line 25
   at AssetRipper.Core.Structure.GameStructure.GameStructureProcessor.ProcessSchemes(GameCollection fileCollection) in C:\Users\Jeremy\source\repos\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructureProcessor.cs:line 89
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(List`1 paths, LayoutInfo layinfo) in C:\Users\Jeremy\source\repos\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 88
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, LayoutInfo layinfo) in C:\Users\Jeremy\source\repos\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 36
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths) in C:\Users\Jeremy\source\repos\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 26
   at AssetRipper.GUI.MainWindow.LoadFiles(Object data) in C:\Users\Jeremy\source\repos\AssetRipper\AssetRipperGUI\MainWindow.xaml.cs:line 98

**Comment by ds5678** [comment] 2021-09-13 15:29
Duplicate of #83 and #84

**Closed by ds5678** 2021-09-13 15:29 UTC
