### ISSUE TITLE
does not rip

### ISSUE THREAD

**Issue by obertin18** [ds5678/AssetRipper#30] opened 2021-08-10 21:47 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

Unity 2019.4.29f1 (64-bit)

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

does not rip

### Relevant log output

Game name: (please, specify the game name)
Engine version: (specify engine version, if known)
Platform: (specify platform, if known)

Error message: Read 24 but expected 219

Stack trace:    at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadMetadata(Stream stream, Int32 metadataSize) in E:\repos\AssetRipper\AssetRipperCore\Parser\Files\BundleFile\BundleFileScheme.cs:line 182
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadFileStreamMetadata(Stream stream, Int64 basePosition) in E:\repos\AssetRipper\AssetRipperCore\Parser\Files\BundleFile\BundleFileScheme.cs:line 161
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream) in E:\repos\AssetRipper\AssetRipperCore\Parser\Files\BundleFile\BundleFileScheme.cs:line 63
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream, String filePath, String fileName) in E:\repos\AssetRipper\AssetRipperCore\Parser\Files\BundleFile\BundleFileScheme.cs:line 34
   at AssetRipper.Core.Structure.SchemeReader.ReadScheme(SmartStream stream, String filePath, String fileName) in E:\repos\AssetRipper\AssetRipperCore\Structure\SchemeReader.cs:line 51
   at AssetRipper.Core.Structure.SchemeReader.LoadScheme(String filePath, String fileName) in E:\repos\AssetRipper\AssetRipperCore\Structure\SchemeReader.cs:line 19
   at AssetRipper.Core.Structure.GameStructure.GameStructure.ProcessPlatformStructure(GameStructureProcessor processor, PlatformGameStructure structure) in E:\repos\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 176
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(List`1 paths, LayoutInfo layinfo) in E:\repos\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 59
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, LayoutInfo layinfo) in E:\repos\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 37
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths) in E:\repos\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 26
   at AssetRipper.GUI.MainWindow.LoadFiles(Object data) in E:\repos\AssetRipper\AssetRipperGUI\MainWindow.xaml.cs:line 98

**Comment by CyberAndrii** [comment] 2021-08-10 22:09
Duplicate of https://github.com/ds5678/AssetRipper/issues/16

**Comment by ds5678** [comment] 2021-08-19 00:53
Hi, this should have been resolved in a recent commit. If your issue persists on the latest alpha build, please post a new issue.

**Closed by ds5678** 2021-08-19 00:53 UTC
Labels: bug
